version: "3.9"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: ${GOMAXPROCS}
  # App
  APP_NAME: ${APP_NAME}
  APP_VERSION: ${APP_VERSION}
  # Logger
  LOG_LEVEL: ${LOG_LEVEL}
  # gRPC
  GRPC_PORT: ${GRPC_PORT}
  # DB
  DB_URL: ${DB_URL}

services:
  app:
    container_name: app
    platform: linux/amd64
    pid: "host"
    build:
      context: .
    environment:
      <<: *x-backend-app-environment
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    env_file:
      - .env

volumes:
  db_data:
